name: 'configure-aws-codeartifact'
description: 'custom Github Action to use AWS CodeArtifact token in Github Actions Workflow'
inputs:
  domain:
    description: 'CodeArtifact domain'
    required: true
  domain-owner:
    description: 'CodeArtifact domain-owner'
    required: true
  duration-seconds:
    description: 'authorization token duration in seconds'
    required: false
    default: '3600'
outputs:
  endpoint-pypi:
    description: 'pypi endpoint'
runs:
  using: 'node16'
  main: 'dist/index.js'
